export const START_LOADING_TODOS = 'START_LOADING_TODOS';
export const GET_TODOS = 'GET_TODOS';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export const IS_ERROR = 'IS_ERROR';
